name: "The United States Web Design System (USWDS) 3.0 Hugo Theme"
license: "CCO"
licenselink: "https://github.com/GSA/uswds-hugo/blob/main/LICENSE.md"
description: "A hugo theme based on the United States Web Design System (USWDS) v3"
homepage: "https://github.com/GSA/uswds-hugo"
tags:
features:
author:
  name: "David Waltermire"
  homepage: "https://github.com/david-waltermire"
original:
  repo: "https://github.com/usnistgov/hugo-uswds"
based:
  name: "The United States Web Design System (USWDS) v3"
  homepage: "https://designsystem.digital.gov/"
  repo: "https://github.com/uswds/uswds"
module:
  hugoVersion:
    min: 0.139.3
    extended: true
  mounts:
  - source: dist/js
    target: static/module/hugo-uswds/js
  - source: dist/css
    target: static/module/hugo-uswds/css
  - source: dist/img
    target: static/module/hugo-uswds/img
  - source: dist/img
    target: assets/module/hugo-uswds/img
  - source: dist/fonts
    target: static/module/hugo-uswds/fonts
  - source: layouts
    target: layouts
  - source: archetypes
    target: archetypes/module/hugo-uswds
