name: Question
description: Ask your question
labels: ['question']
body:
  - type: textarea
    id: question-text
    attributes:
      label: Question
      description: Please enter your question
    validations:
      required: true
