# Default page title
title: "Hugo USWDS"
baseURL: https://gsa.gov/hugo-uswds/ # The base URL of the site
#canonifyurls: true # Creates absolute URLs for all links in the site
defaultContentLanguage: en # The default language provided by the site
languageCode: "en-us"
googleAnalytics: UA-66610693-1 # If provided, the site will use Google Analytics
# Establishes page file metadata based on Git commits info
# for the associated file
enableGitInfo: true
# Indicates that metadata provided in page headers is provided
# in YAML
MetaDataFormat: "yaml"
enableRobotsTXT: true
# There are two main navigation menus that can be configured
# here. "primary" menu entries appear in the main navigation
# provided by the Basic and Extended Headers. "secondary" menu
# entries appear in the Extended Header on the homepage.
# Navigation can also be configured on any corresponding pages.
menu:
  secondary:
    - name: Github
      url: https://github.com/GSA/uswds-hugo
      weight: 90
# Configures this theme
module:
  imports:
    - path: "github.com/GSA/hugo-uswds"
# The following custom parameters are used by the page
# templates and components.
params:
  # Configures the content used in the Basic and Extended
  # Header components.
  header:
    # An optional short name for the site for use on the basic
    # Header. If not provided, the project_name will be used
    # instead.
    project_shortname: "USWDS Hugo Theme"
    project_name: "United States Web Design System Hugo Theme"
  # Used to provide the "Improve this Page" link on the bottom
  # of each page. This setting is optional. If not provided,
  # the "Improve this Page" link will not be provided
  contentRepoPath: https://github.com/GSA/uswds-hugo/tree/master/website/content
  # Used to configure the search bar to use search.gov
  searchAffiliate: metaschema
markup:
  goldmark: # Markdown Rendering
    renderer:
      unsafe: true # required for the Hugo USWDS theme
  highlight: # Code Highlighting
    guessSyntax: true
    noClasses: false # enables USWDS styled syntax highlighting