name: Validate Repo Markdown
on:
  workflow_call:
    inputs:
      ignorePattern:
        description: 'a pattern provided to grep for files/directories to ignore'
        required: false
        default: '^website/'
        type: string
      linkcheck_fail_on_error:
        description: 'a boolean flag that determines if bad links found by the link checker fail fast and stop a complete build'
        required: false
        default: true
        type: boolean
      linkcheck_create_issue:
        description: 'create new GitHub issue if broken links found'
        required: false
        default: false
        type: boolean
jobs:
  validate-repo-markdown:
    name: Validate Repo Markdown
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      issues: write
    steps:
    # use this for pulls where checkout is anonymous
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        submodules: recursive
    # Build Artifacts
    # ---------------
    - name: Identify Markdown files
      id: markdownfiles
      run: echo "files=$(git ls-files "*.md" -z | grep  -v "${{ inputs.ignorePattern }}" --null-data | tr '\0' ' ')" >> $GITHUB_OUTPUT
    - id: linkchecker
      name: Link Checker
      uses: lycheeverse/lychee-action@ec3ed119d4f44ad2673a7232460dc7dff59d2421
      with:
        args: --exclude-file .github/workflows/config/.lycheeignore --verbose --no-progress --accept 200,206,429 ${{ steps.markdownfiles.outputs.files }} --exclude-mail
        format: markdown
        output: markdown-link-report.md
        debug: true
        fail: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
    - name: Create issue if bad links detected
      if: ${{ !cancelled() && env.lychee_exit_code != 0 && inputs.linkcheck_create_issue }}
      uses: peter-evans/create-issue-from-file@433e51abf769039ee20ba1293a088ca19d573b7f
      with:
        title: Scheduled Check of Markdown Documents Found Bad Hyperlinks
        content-filepath: markdown-link-report.md
        labels: |
          bug
          documentation
    - name: Fail on link check error
      if: ${{ !cancelled() && env.lychee_exit_code != 0 && (github.event.inputs.linkcheck_fail_on_error == 'true' || inputs.linkcheck_fail_on_error == true) }}
      uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410
      with:
        script: |
          core.setFailed('Link checker detected broken or invalid links, read attached report.')
